builder:
  image: tutum/builder
  volumes:
    - ~/.docker:/.docker:ro
  environment:
    - GIT_REPO=https://github.com/VyronLee/dockerfiles.git
    - DOCKERFILE_PATH=/test
    - IMAGE_NAME=VyronLee/test:latest
  privileged: true
